name: JS Actions

on:
  issues:
    types: [labeled]

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: test
        run: "npm install --save request request-promise @actions/core"
      - name: ha-ha
        uses: ./.github/actions/joke-action
